### ISSUE TITLE
Missing transPHLA_train_len9.txt

### ISSUE THREAD

**Issue by ahof1704** [PRBorole/MHCXAI#1]
Hi,

I am trying to run your notebook `1 - MHCXAI usage and instance based explanations`. I am running into the following error: 
`FileNotFoundError: ../transPHLA/TransPHLA-AOMP/transPHLA_train_len9.txt not found.`

Could you point out where I can find the mentioned file? 
Thanks

**Comment by PRBorole** [comment]
Hi,

For TransPHLA, we used the training file from the GitHub repository: https://github.com/a96123155/TransPHLA-AOMP/blob/master/Dataset/train_set.zip. From this file, we only selected the peptides with a length of 9 and stored the filtered list (just the peptides) as 'transPHLA_train_len9.txt'.

We will update the README to include information about the training files soon.

**Comment by ahof1704** [comment]
Great. Thanks! 

One more question: I would like to evaluate the immunogenicity capacity of my protein sequences and identify which segments of a protein are the hot spots for that. My proteins are as long as 100 AA long. Would you recommend I break it into segments of 9 AA? 

thanks

**Comment by PRBorole** [comment]
As most peptides MHC class I molecule presents are of length 9, it is a good choice. However, they are capable of presenting peptides of length 8-15. 

Checkout NetMHCpan: https://services.healthtech.dtu.dk/services/NetMHCpan-4.1/ 
Here you can pass your entire sequence as fasta seq and select peptides of multiple lengths. It automatically divides the sequence and calculates binding affinitie against your MHC molecule of interest.

**Comment by ahof1704** [comment]
Very interesting! Breaking my sequences into segments of 9 amino acids is not a problem. In fact, I would like to be able to use all the methods you listed in your paper, so it is better if I do that. 

is there a quick way to test the binding affinity against all the known human MHC molecules using your framework?

**Comment by PRBorole** [comment]
Hi,

Unfortunately, I am not aware of a quick way to test BA against all HLAs and neither can MHCXAI do that.
